name: Auto Format

on:
  push:
    branches: [ master , CI_testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up R '4.1.1'
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: '4.1.1'
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Auto Format R directory with formatR
        run: formatR::tidy_dir("R", indent=2, arrow=TRUE)
        shell: Rscript {0}
